name: msCD
# 'on':
#   push:
#     branches:
#       - main
#     paths:
#       - .github/workflows/cd.yml
# env:
#   RELEASE_TAG: shipping-0.0.6
#   REPOSITORY_NAME: ${{ github.event.head_commit.message }}
on:
  repository_dispatch:
    # types: msDeploy
# jobs:
#   myEvent:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ github.event.client_payload.ref }}
#       - run: echo ${{ github.event.client_payload.sha }}
env:
  RELEASE_TAG: ${{ github.event.client_payload.tag }}
  REPOSITORY_NAME: ${{ github.event.client_payload.repo }}
jobs:
  download_release_and_deploy:
    # if: github.event.head_commit.author.name == 'Github Actions'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dowload release artifact
        uses: robinraju/release-downloader@v1.4
        with:
          repository: Obligatorio-ORT-FI-8184-DevOps/${{ env.REPOSITORY_NAME }}
          tag: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: drahtul/demo-app
          tags: ${{ env.RELEASE_TAG }}
          dockerfile: micros/Dockerfile
          registry: docker.io
          username: drahtul
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Update Image Version in deployment.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: micros/${{ env.REPOSITORY_NAME }}/deployment.yaml
          propertyPath: $.spec.template.spec.containers[0].image
          value: drahtul/demo-app:${{ env.RELEASE_TAG }}
          branch: main
          message: 'Auto-commit: ms deployed'
